services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: prostoy
      POSTGRES_PASSWORD: damir_999
      POSTGRES_DB: docsearch_db
      POSTGRES_INITDB_ARGS: "--no-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prostoy -d docsearch_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep status"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pip install -r requirements.txt && sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - NAME=docsearch_db
      - USER=prostoy
      - PASSWORD=damir_999
      - HOST=db
      - PORT=5432

volumes:
  postgres_data:
  es_data:
