# Generated by Django 4.2.16 on 2025-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rubrics', models.JSONField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
